name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: scheduling/backend

      - name: Build project
        run: npm run build
        working-directory: scheduling/backend

      - name: Copy build to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "scheduling/backend/dist/*"
          target: "/home/ec2-user/apps/Scheduling/backend/dist"

      - name: Restart backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            pm2 restart scheduling-backend || pm2 start dist/main.js --name scheduling-backend
            pm2 save



