name: Deploy Backend

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Build project
        run: npm run build
        working-directory: backend

      - name: Copy dist to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "backend/dist"
          target: "/home/ec2-user/apps/Scheduling/backend"
          rm: true

      - name: Restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/apps/Scheduling/backend

            if [ -f dist/index.js ]; then
              pm2 restart scheduling-backend || pm2 start dist/index.js --name scheduling-backend
              pm2 save
            else
              echo "dist/index.js not found!"
              exit 1
            fi